Repository salesforce/Argus, pull requests merged in 2018-07, with the labels that each got.

#800 Update Argus about page on the UI
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/DiscoveryService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryService.java
  ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryServiceTest.java
  ArgusWeb/app/js/config.js
  ArgusWeb/app/js/directives/controls/dashboard.js
  ArgusWeb/app/js/templates/about.html
  ArgusWeb/config/config.js
  ArgusWeb/package-lock.json
  ArgusWeb/package.json
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AuthResourcesV2.java
Labels: cla:missing, documentation

#811 Change discovery service to lookup scopes index
  .gitignore
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecordQuery.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/MonitorService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java
  ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaServiceTest.java
Labels: cla:signed

#818 Update dashboard markup editor and add attribute to ag-metric
  ArgusWeb/app/css/main.css
  ArgusWeb/app/index.html
  ArgusWeb/app/js/controllers/dashboardsDetail.js
  ArgusWeb/app/js/controllers/viewElements.js
  ArgusWeb/app/js/directives/charts/metric.js
  ArgusWeb/app/js/services/charts/dataProcessing.js
  ArgusWeb/app/package-lock.json
  ArgusWeb/app/package.json
  ArgusWeb/webpack_index.html
Labels: cla:missing, feature

#813 Sync TSD write-endpoints iterable and customizable logback output file names
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBService.java
  ArgusCore/src/test/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBServiceTest.java
  src/main/resources/META-INF/logback.xml
Labels: cla:signed

#828 Release/2.15.0
  .travis.deploy.sh
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Alert.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/DistributedSchedulingLock.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/AlertDefinitionsCacheRefresherThread.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/DefaultMetricService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/schedule/DistributedDatabaseSchedulingService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/CachedDiscoveryService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemConfiguration.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/util/Cron.java
  ArgusCore/src/main/javacc/MetricReader.jj
  ArgusCore/src/test/java/com/salesforce/dva/argus/util/CronTest.java
  README.md
Labels: cla:signed

#827 Fix all javadocs so Maven javadoc builds
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Alert.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Audit.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Chart.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/DistributedSchedulingLock.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/GlobalInterlock.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/History.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/JPAEntity.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Namespace.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Notification.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/AlertService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/DashboardService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/DiscoveryService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/DistributedSchedulingLockService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/ManagementService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/SchemaService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/CallbackNotifier.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/DefaultNotifier.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/callback/Pool.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/AliasTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/AnomalyDetectionRPCATransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/ConsecutiveValueMapping.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DerivativeValueMapping.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DeviationValueReducerOrMapping.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DownsampleTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/ExcludeTransformWrap.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillCalculateTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/IncludeTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/LogValueMapping.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricDistiller.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricFilterWithInteralReducerTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricReducerOrMappingTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricReducerOrMappingWithConstantTransform.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/NormalizeTransformWrap.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/ValueZipper.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/monitor/DefaultMonitorService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/schedule/DistributedZookeeperSchedulingService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/CachedTSDBService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/MetricQuery.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/users/CachedUserService.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/util/HBaseUtils.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/util/zookeeper/Barrier.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/util/zookeeper/ClientNode.java
  ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/ArgusService.java
  ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/AuthService.java
  ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/entity/History.java
  ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/exceptions/TokenExpiredException.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/AuditDto.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/HistoryDTO.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AlertResources.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AuthResources.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/ChartResources.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DashboardResources.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DiscoveryResources.java
  ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/ManagementResources.java
Labels: cla:signed

#825 Customized argus alert trigger name
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/DefaultNotifier.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java
  ArgusCore/src/test/java/com/salesforce/dva/argus/service/NotifierTest.java
Labels: cla:signed

#829 Formatting Event Text in Email and GOC for better visualisation
  ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Trigger.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/EmailNotifier.java
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java
Labels: cla:signed

#836 Support displaying empty time range at the beginning or the end of a graph
  ArgusWeb/app/js/controllers/alertsDetail.js
  ArgusWeb/app/js/directives/charts/chart.js
  ArgusWeb/app/js/directives/charts/lineChart.js
  ArgusWeb/app/js/services/charts/chartElements.js
  ArgusWeb/app/js/services/charts/chartTools.js
  ArgusWeb/app/js/templates/dashboard-detail.html
  ArgusWeb/app/js/templates/modals/chartOptions.html
Labels: enhancement

#838 Bug filltransform
  ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillTransform.java
  ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/FillTransformTest.java
Labels: cla:signed

#850 Use actual verion instead of project.version since maven is not refle…
  ArgusClient/pom.xml
  ArgusCore/pom.xml
  ArgusSDK/pom.xml
  ArgusWeb/pom.xml
  ArgusWebServices/pom.xml
  pom.xml
Labels: cla:signed

#851 Use actual verion instead of project.version since maven is not refle…
  ArgusClient/pom.xml
  ArgusCore/pom.xml
  ArgusSDK/pom.xml
  ArgusWeb/pom.xml
  ArgusWebServices/pom.xml
  pom.xml
Labels: cla:signed

#852 Use actual verion instead of project.version since maven is not refle…
  ArgusClient/pom.xml
  ArgusCore/pom.xml
  ArgusSDK/pom.xml
  ArgusWeb/pom.xml
  ArgusWebServices/pom.xml
  pom.xml
Labels: cla:signed

#854 maven deploy with same version fails: Repository ='releases:Releases'…
  ArgusClient/pom.xml
  ArgusCore/pom.xml
  ArgusSDK/pom.xml
  ArgusWeb/pom.xml
  ArgusWebServices/pom.xml
  pom.xml
  project.version
Labels: cla:signed

#858 Update to specific pom version 2.17.1
  ArgusClient/pom.xml
  ArgusCore/pom.xml
  ArgusSDK/pom.xml
  ArgusWeb/pom.xml
  ArgusWebServices/pom.xml
  pom.xml
  project.version
Labels: cla:signed
